### ISSUE TITLE
Nothing left to do

### ISSUE THREAD

**Issue by MasterICT** [MasterICT/DesignPatternsProject#1]
I feel a bit useless, can you un-implement something so I know what to do other than doing class diagrams? 

Thanks!!

**Comment by masterictFS** [comment]
Maybe an implementation of the Adapter pattern in order to handle payments with different (fake) clients?

[Shameless php "inspiration"](https://code.tutsplus.com/tutorials/design-patterns-the-adapter-pattern--cms-22262)

**Comment by MasterICT** [comment]
I read this suggestion with a lot of latency, and I already implemented the Adapter pattern for another part of the application (#2). Let me know if that makes sense to you!
